.gitignore
Tester/Tester.csproj

* Changed `Tester.csproj` to be a .NET Core app
* Added `.vs` to `.gitignore`
This closes #1

Update Tester to be a .NET Core App

---

TorchSharp/TypeGeneration.cs
TorchSharp/TypeGeneration.tt

This is needed to implement Resize in SNT #13

Adding newWithResizeX

---

Test/BasicTensorAPI.cs
Test/MatrixAndVectorOps.cs
Test/UnaryTensorOps.cs
TorchSharp/TypeGeneration.tt

With this PR, the basic tensor functionality for floating point tensors have unit test coverage.

Basic Unit Tests Done

---

TorchSharp/TypeGeneration.cs
TorchSharp/TypeGeneration.tt

Fix to the cross product.

---

Test/BasicTensorAPI.cs
TorchSharp/TypeGeneration.cs
TorchSharp/TypeGeneration.tt

* Unit tests for newWithStorage
* Fix to Storage_newWithSize
* Fix to Storage parameter (now it avoid the creation of multiple objects when called multiple times)
* Added Retain and Size
* Misc

Additional unit tests plus tensor storage methods

---

TorchSharp/Raw/Lapack.generated.cs
TorchSharp/Raw/Lapack.tt
TorchSharp/TorchSharp.csproj

[issue #23] Implement low-level bindings for THLapack_* functions

---

src/Examples/MNIST.cs

output => prediction

---

src/AtenSharp/Raw/Types.ttinclude
src/AtenSharp/Raw/Vector.tt
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/Native/LibTorchSharp/Utils.h
src/TorchSharp/NN/LossFunction.cs
src/TorchSharp/NN/MaxPool2D.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/ReLu.cs
src/TorchSharp/Scalar.cs
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/Tensor/Types.ttinclude
src/TorchSharp/Torch.cs
test/TorchSharpTest/TorchSharp/TorchSharp.cs

This fills in some missing operations on TorchTensor.
@interesaaat Let me know what you think

Add additional operations to TorchTensor

---

azure-pipelines.yml

building the massive redist packages is really very expensive and flakey in CI

no build packages on prs or branches

---

src/Native/LibTorchSharp/THSTensor.cpp
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TorchSharp.cs

Add some tests that we are disposing of memory

add some memory tests

---

src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/Losses.cs
src/TorchSharp/Scalar.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TorchSharp.cs

make TorchTensor a class (to avoid memory leaks)

---

src/Native/LibTorchSharp/Utils.h
test/TorchSharpTest/TorchTensor.cs

This improves error messages for some cases that fail on GPU, see https://github.com/DiffSharp/DiffSharp/issues/147#issuecomment-651118037

better error messages

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

- CumulativeMax/Min/Sum/Prod
- Gamma functions
- dist, expm1, erf, erfc, erfinv
- fft 
- frac, fmod, lerp
- logical_and/or/not/xor
- prelu, rsqrt, inplce sigmoid
- log1p

more functions

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

This gives the ability to fill tensors in place with random values

in place randoms

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

* arange_out (mutating)
* ifft, rfft, irfft

add more functions

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

Hi, this is my first PR. Just wanna to make sure I'm understanding the project correctly.

Added torch.gcd & torch.lcm

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

Add celu, leaky_relu, silu, selu, elu, gelu, hardtanh, hardswish, hardsigmoid

add more activation functions

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

adds avgpool1d, 2d, 3d and backward mode for these

add avgpool

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs

add logcumsumexp, logsigmoid, adaptive avg pool
Also permute, split_with_size

add logcumsumexp, logsigmoid

---

src/Native/LibTorchSharp/THSTensor.cpp
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/NN.cs

The divisor was being set to zero in this function, if not being set explicitly

fix avgpool backward

---

test/TorchSharpTest/TestTorchTensor.cs

Add new cuda tests trying to track down the bug in https://github.com/DiffSharp/DiffSharp/pull/294

add new cuda tests

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Optimizer.cs
test/TorchSharpTest/NN.cs

Added RMSprop and Adagrad optimizers and corresponding unit tests.

Optimizers

---

src/Examples/AlexNet.cs
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/AdaptiveAvgPool1D.cs
src/TorchSharp/NN/AdaptiveAvgPool2D.cs
src/TorchSharp/NN/AdaptiveAvgPool3D.cs
src/TorchSharp/NN/AdaptiveMaxPool1D.cs
src/TorchSharp/NN/AdaptiveMaxPool2D.cs
src/TorchSharp/NN/AdaptiveMaxPool3D.cs
src/TorchSharp/NN/AvgPool1D.cs
src/TorchSharp/NN/AvgPool3D.cs
src/TorchSharp/NN/BatchNorm1D.cs
src/TorchSharp/NN/BatchNorm2D.cs
src/TorchSharp/NN/BatchNorm3D.cs
src/TorchSharp/NN/Conv1D.cs
src/TorchSharp/NN/Conv2D.cs
src/TorchSharp/NN/Conv3D.cs
src/TorchSharp/NN/MaxPool1D.cs
src/TorchSharp/NN/MaxPool3D.cs
src/TorchSharp/NN/Optimizer.cs
test/TorchSharpTest/NN.cs

Adding 1D pooling, Conv1D, and BatchNormalization modules and corresponding unit tests.
Closes #188.

Convolution, 1D pooling, BatchNorm

---

src/Examples/AlexNet.cs
src/Examples/MNIST.cs
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/CELU.cs
src/TorchSharp/NN/ELU.cs
src/TorchSharp/NN/GELU.cs
src/TorchSharp/NN/LeakyReLU.cs
src/TorchSharp/NN/RReLU.cs
src/TorchSharp/NN/ReLU6.cs
src/TorchSharp/NN/SELU.cs
src/TorchSharp/NN/SiLU.cs
src/TorchSharp/NN/Sigmoid.cs
src/TorchSharp/NN/Softmax.cs
src/TorchSharp/NN/Softmax2d.cs
src/TorchSharp/NN/Softmin.cs
src/TorchSharp/NN/Tanh.cs
test/TorchSharpTest/NN.cs

Adding modules for the most common activation functions, along with unit tests.
Fixed spelling of 'ReLU' to be the same as in PyTorch.

Activations

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Transformer.cs
src/TorchSharp/NN/TransformerDecoder.cs
src/TorchSharp/NN/TransformerDecoderLayer.cs
src/TorchSharp/NN/TransformerEncoder.cs
src/TorchSharp/NN/TransformerEncoderLayer.cs
test/TorchSharpTest/NN.cs

Adding the Transformer modules.

Transformer

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Dropout.cs
src/TorchSharp/NN/Dropout2d.cs
src/TorchSharp/NN/Dropout3d.cs
src/TorchSharp/NN/Flatten.cs
test/TorchSharpTest/NN.cs

Dropout & Flatten

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Recurrent/GRU.cs
src/TorchSharp/NN/Recurrent/GRUCell.cs
src/TorchSharp/NN/Recurrent/LSTM.cs
src/TorchSharp/NN/Recurrent/LSTMCell.cs
src/TorchSharp/NN/Recurrent/RNN.cs
src/TorchSharp/NN/Recurrent/RNNCell.cs
test/TorchSharpTest/NN.cs

This PR implements RNN, GRU, LSTM, as well as the corresponding *Cell modules.

Recurrent neural networks

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

See #180 for a list of features introduced in v1.6.0 of PyTorch. This PR addresses a number of them, but not all.

Adding a number of missing v1.6.0 features

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/NN/Unflatten.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

This will add many of the v1.7.0 features tracked in #179. The PR subsumes #237.

Adding a number of missing v1.7.0 features

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs

This addresses many of the missing operations mentioned in #238.

Adding a few missing 1.8.0 operations

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
test/TorchSharpTest/TestTorchTensor.cs

There was a number of missing tensor factory methods, as well as some more obscure operators, such as the spectral window operators.
The set of random number distributions should be fairly complete right now.

Adding miscellaneous missing operators.

---

src/Native/LibTorchSharp/THSRandom.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTensorFactories.cpp
src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.handwritten.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/Tensor/Types.ttinclude
src/TorchSharp/TorchScalar.cs
test/TorchSharpTest/TestTorchTensor.cs

This is a first draft PR for complex number support. At this point, you can create, do arithmetic, and convert complex tensors.
The really interesting work will be FFTs for signal processing, but I will add that in a later PR. This is just the basic stuff.

Complex number support

---

src/Native/LibTorchSharp/THSLoss.cpp
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/CosineSimilarity.cs
src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/PairwiseDistance.cs
src/TorchSharp/Tensor/TorchTensor.Math.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

amin(), amax(), complex(), and polar() were all missing. Now they're not.

Adding missing functions.

---

src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/TorchScalar.cs

Addressing issue #269

---

src/Native/LibTorchSharp/CMakeLists.txt
src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSSpecial.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/Special.cs
src/TorchSharp/Tensor/TorchTensor.LinearAlgebra.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/Tensor/Types.ttinclude
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

Adding torch.special namespace.
Adding a couple of linalg functions.
Fixed a bug in constructing complex tensors from arrays.
Added a few convenience overloads for arange, zeros, ones, empty, full, rand, randn.

A first batch of 1.9 additions.

---

test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

skip failing tests on mac

---

pkg/FileRestitcher/FileRestitcher.Tests/UnitTest1.cs

Fix the restitcher test, also disable it for now

Fix the restitcher test

---

src/TorchSharp/NN/AlphaDropout.cs
src/TorchSharp/NN/Bilinear.cs
src/TorchSharp/NN/CosineSimilarity.cs
src/TorchSharp/NN/Dropout.cs
src/TorchSharp/NN/Dropout2d.cs
src/TorchSharp/NN/Dropout3d.cs
src/TorchSharp/NN/FeatureDropout.cs
src/TorchSharp/NN/Identity.cs
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/PairwiseDistance.cs
src/TorchSharp/NN/PixelShuffle.cs
src/TorchSharp/NN/PixelUnshuffle.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool1D.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool2D.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool3D.cs

Issue #319 -- some functions were located in the wrong namespace

---

src/Examples.Utils/CIFARReader .cs
src/Examples/AlexNet.cs
src/Examples/CIFAR10.cs
src/Examples/MobileNet.cs
src/Examples/Program.cs
src/Examples/Properties/launchSettings.json
src/Examples/ResNet.cs
src/Examples/VGG.cs
src/FSharp.Examples/AlexNet.fs
src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTensorMath.cpp
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Pooling/AvgPool1D.cs
src/TorchSharp/NN/Pooling/AvgPool2D.cs
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/Tensor/Tensor.LinearAlgebra.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/TorchVision/AdjustHue.cs
src/TorchSharp/TorchVision/Functional.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

torch.linalg.cond
torch.linalg.cholesky_ex
torch.linalg.inv_ex
torch.amax/amin
torch.matrix_exp
Adding support for tensor min/max in clamp.

Adding another few of the missing operators in1.6 - 1.9

---

src/TorchSharp/Torch.cs

@NiklasGustafsson We need to find a better way to fix this....  I'll add an issue

Fix hardwired version in Torch.cs

---

Directory.Build.props
src/TorchSharp/Torch.cs
src/TorchSharp/TorchSharp.csproj

better native load diagnostics, help ensure versions match

---

src/Native/LibTorchSharp/THSModule.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Module.cs

Fixed a couple of incorrectly implemented APIs.
Added RegisterParameter()

Module: missing / incorrect APIs

---

Directory.Build.props
build/BranchInfo.props
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/RELEASENOTES.md
src/TorchSharp/NN/Losses.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Also, updating the release notes and taking explicit control over the patch version number.

Fixing #353

---

RELEASENOTES.md
src/TorchSharp/NN/Module.cs

This change allows custom module implementations of state_dict() and load() to enable state outside class fields.

Virtualized module serialization.

---

RELEASENOTES.md
docfx/articles/modules.md
docfx/index.md
src/Examples/AlexNet.cs
src/Native/LibTorchSharp/THSModule.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/ModuleDict.cs
src/TorchSharp/NN/ModuleList.cs
src/TorchSharp/NN/Parameter.cs
src/TorchSharp/NN/ParameterDict.cs
src/TorchSharp/NN/ParameterList.cs
src/TorchSharp/Tensor/Tensor.LinearAlgebra.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.Trig.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/TorchSharp.csproj
test/TorchSharpTest/NN.cs

Adding {Module|Parameter}{List|Dict}

Modules -- a more complete implementation.

---

docfx/articles/modules.md
src/Examples/SequenceToSequence.cs
src/Examples/TextClassification.cs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs

Trivial PR -- affecting comments only.

Adjusted instructions on how to download data files for the examples.

---

src/Examples/Properties/launchSettings.json
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Transformer.cs
src/TorchSharp/NN/TransformerDecoder.cs
src/TorchSharp/NN/TransformerDecoderLayer.cs
src/TorchSharp/NN/TransformerEncoder.cs
src/TorchSharp/NN/TransformerEncoderLayer.cs
test/TorchSharpTest/NN.cs

Removed a mysterious 'NullTensor' field in a number of Transformer layers.

Fixed bug in module, buffer, and parameter registration

---

docfx/articles/modules.md
src/Examples/CIFAR10.cs
src/Examples/SequenceToSequence.cs
src/Examples/TextClassification.cs
src/TorchSharp/NN/Sequential.cs

I made some minor improvements to a couple of the examples, and updated the modules.md article.
Changed a comment in Sequential.cs

Minor improvements to examples

---

src/FSharp.Examples/AlexNet.fs
src/FSharp.Examples/MNIST.fs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSOptimizers.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.Trig.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

Fixed the 'step()' function interface. It should return a Tensor if there's a closure passed in.

Implemented missing optimizers.

---

src/TorchSharp/TorchVision/Erase.cs
src/TorchSharp/TorchVision/Functional.cs
src/TorchSharp/TorchVision/Posterize.cs
src/TorchSharp/TorchVision/Resize.cs
src/TorchSharp/TorchVision/Solarize.cs

Use functional methods for Transform

---

README.md
RELEASENOTES.md
azure-pipelines.yml
docfx/articles/memory.md
src/Examples/AlexNet.cs
src/Examples/MNIST.cs
src/Examples/Properties/launchSettings.json
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

Also updated README and azure-pipelines.yaml.

Fixed missing temporaries Dispose in Sequential.forward()

---

.gitignore
RELEASENOTES.md
TorchSharp.sln
src/TorchSharp/DisposeScope.cs
src/TorchSharp/DisposeScopeManager.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/ThreadDisposeScopeStatistics.cs
src/TorchSharp/Utils/ObjectReferenceEqualityComparer.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestDisposeScopes.cs
test/TorchSharpTest/TestTorchTensor.cs

Fixed a lot of code review issues and cleaned up the commits. Sorry for the multiple PRs, I think I managed to cover all the review comments from the previous PR.

Dispose Scope

---

src/Examples/SequenceToSequence.cs
src/Examples/TextClassification.cs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSNormalization.cpp
src/TorchSharp/NN/Bilinear.cs
src/TorchSharp/NN/Convolution/Conv1D.cs
src/TorchSharp/NN/Convolution/Conv2D.cs
src/TorchSharp/NN/Convolution/Conv3D.cs
src/TorchSharp/NN/Convolution/ConvTranspose1D.cs
src/TorchSharp/NN/Convolution/ConvTranspose2D.cs
src/TorchSharp/NN/Convolution/ConvTranspose3D.cs
src/TorchSharp/NN/Embedding.cs
src/TorchSharp/NN/EmbeddingBag.cs
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/Normalization/BatchNorm1D.cs
src/TorchSharp/NN/Normalization/BatchNorm2D.cs
src/TorchSharp/NN/Normalization/BatchNorm3D.cs
test/TorchSharpTest/NN.cs

Also, correcting the spelling or 'weight' and 'bias' on modules that have them.

Fixing BatchNorm{123}d -- adding weight/bias/running_mean/running_var/reset_running_stats

---

RELEASENOTES.md
build/BranchInfo.props
docfx/articles/saveload.md

Updated release notes, the article on model save / load.
Update the version number.

Release preparation

---

src/TorchSharp/DataLoader.cs
test/TorchSharpTest/TestDataLoader.cs

This will clean up temporaries before returning data from the DataLoader.

Explicit memory management in DataLoader.MoveNext()

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSActivation.cpp
src/Native/LibTorchSharp/THSConvolution.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Activation/ChannelShuffle.cs
src/TorchSharp/NN/Activation/GLU.cs
src/TorchSharp/NN/Activation/Hardshrink.cs
src/TorchSharp/NN/Activation/Hardsigmoid.cs
src/TorchSharp/NN/Activation/Hardtanh.cs
src/TorchSharp/NN/Activation/Softplus.cs
src/TorchSharp/NN/Activation/Softshrink.cs
src/TorchSharp/NN/Activation/Softsign.cs
src/TorchSharp/NN/Activation/Tanhshrink.cs
src/TorchSharp/NN/Activation/Threshold.cs
src/TorchSharp/NN/Pooling/LPPool1d.cs
src/TorchSharp/NN/Pooling/LPPool2d.cs
src/TorchSharp/NN/Pooling/MaxUnpool1d.cs
src/TorchSharp/NN/Pooling/MaxUnpool2d.cs
src/TorchSharp/NN/Pooling/MaxUnpool3d.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

Addressing #554, #555, #556, and #559

Missing pooling, activation, and miscellaneous layers.

---

src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.LinearAlgebra.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTorchTensor.cs

Miscellaneous missing functions

---

RELEASENOTES.md
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

Issue #566

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/NN/Module.cs
test/TorchSharpTest/TestLoadSave.cs

Support load_state_dict()
Modified version number.
Updated release notes.

Support load_state_dict()

---

docfx/articles/saveload.md

Related to https://github.com/dotnet/TorchSharp/pull/552

Updated doc: added document about importing TorchSharp format models into Python?

---

src/TorchSharp/NN/Module.cs

done some cleanup in Module.cs. Want to have feedback what kind of cleanup is welcome and which one might not, before doing cleanup in other places.

cleaning up Module.cs

---

RELEASENOTES.md
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/TorchVision/models/AlexNet.cs
src/TorchSharp/TorchVision/models/GoogleNet.cs
src/TorchSharp/TorchVision/models/InceptionV3.cs
src/TorchSharp/TorchVision/models/ResNet.cs
src/TorchSharp/TorchVision/models/VGG.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchVision.cs

Adding torchvision.models.googlenet()

---

RELEASENOTES.md
src/TorchSharp/Device.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Torch.cs
test/TorchSharpTest/TestTorchTensor.cs

Adding support for the 'meta' device type.

Meta device type

---

RELEASENOTES.md
src/TorchSharp/NN/Vision.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/TorchVision/Functional.cs
test/TorchSharpTest/NN.cs

Fixed incorrection implementation of pad().

---

pkg/TorchSharp/TorchSharp.nupkgproj

Fixes https://github.com/dotnet/TorchSharp/issues/629

Fix TorchSharp package dependencies

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/GlobalSuppressions.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

adding missing `std_mean` methods to the C++ files and in the C# file. 
Open issues: 
* check if build is working
* implement unit tests

implementation of std_mean

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/Recurrent/GRU.cs
src/TorchSharp/NN/Recurrent/LSTM.cs
src/TorchSharp/NN/Recurrent/RNN.cs
src/TorchSharp/NN/Vision.cs
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/TorchVision/Functional.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

Adding ReadOnlySpan<long> overloads in advantageous locations.

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/Utils.h
src/TorchSharp/NN/Utils/PackedSequence.cs
src/TorchSharp/NN/Utils/RNNUtils.cs
test/TorchSharpTest/TestNNUtils.cs

- torch.nn.utils.rnn.pack_padded_sequence
- torch.nn.utils.rnn.pad_packed_sequence
- torch.nn.utils.rnn.pad_sequence
- torch.nn.utils.rnn.pack_sequence

Added torch.nn.utils.rnn

---

src/TorchSharp/JIT/ScriptModule.cs

Incremental performance improvements.
@tarekgh -- is this what you had in mind on the other PR thread?

Removed unecessary heap allocation of native arguments.

---

src/TorchSharp/Hub.cs

Web client has been deprecated and should to replaced with HttpClient

---

src/TorchSharp/TorchAudio/Functional.cs
src/TorchSharp/TorchAudio/ResamplingMethod.cs
src/TorchSharp/TorchAudio/Transforms.cs
test/TorchSharpTest/TestTorchAudio.cs

Unit tests and doc comments are to be added.

Added `torchaudio.Resample()` and `torchaudio.functional.resample()`.

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

- adding the [var](https://pytorch.org/docs/stable/generated/torch.var.html), and [var_mean](https://pytorch.org/docs/stable/generated/torch.var_mean.html) functions
- fixing some documentation details on `std_mean` functions

adding var and var_mean functions

---

src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Issue #653

---

src/TorchSharp/Tensor/Tensor.Math.cs
test/TorchSharpTest/TestTorchTensor.cs

`torch.le()` of PyTorch is documented in https://pytorch.org/docs/stable/generated/torch.le.html

Add element-wise comparison methods of torch class.

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/TestTorchTensor.cs

- implementing `tensor.isnan()`
- `using System.Diagnostics.Contracts`, because `[PureAttribute]` is often used

implementing isnan

---

azure-pipelines.yml
src/TorchSharp/Tensor/Tensor.Factories.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Fix the performance issue associated with tensor().

Fix performance issue reported in #670

---

RELEASENOTES.md
build/BranchInfo.props

Preparing for release of 0.97.1

Bumping the version number and updating release notes.

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Scalar.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTorchTensor.cs

index_add, index_copy, index_fill

Adding more missing functions.

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs
test/TorchSharpTest/TestTraining.cs

Adding another composite LR scheduler.

SequentialLR

---

src/TorchSharp/Distributions/Categorical.cs
src/TorchSharp/Distributions/Distribution.cs
src/TorchSharp/Distributions/Laplace.cs
src/TorchSharp/Distributions/LogitRelaxedBernoulli.cs
src/TorchSharp/Distributions/OneHotCategorical.cs
test/TorchSharpTest/TestDistributions.cs

Laplace
LogitRelaxedBernoulli
OneHotCategorical

Adding a few more distributions.

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTraining.cs

ReduceLROnPlateau

---

README.md

Btw really appreciate the library, and ongoing efforts to keep in sync with libtorch updates.

Minor: spelling fixes and fully qualified type on example

---

src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTorchTensor.cs

- torch.argmax()
- torch.argmin()
- torch.argsort()
- torch.normal(double, double)
- torch.sum()

Add function methods `torch.sum()`, and etc.

---

src/TorchSharp/TorchAudio/FeatureExtractorNormMode.cs
src/TorchSharp/TorchAudio/Modules/HuBERTPretrainModel.cs
src/TorchSharp/TorchAudio/Modules/Wav2Vec2Components.cs
src/TorchSharp/TorchAudio/Modules/Wav2Vec2Model.cs
src/TorchSharp/TorchAudio/Wav2Vec2Models.cs
test/TorchSharpTest/TestTorchAudioModels.cs

Sample code using a pre-trained model from PyTorch.
```csharp
var model = torchaudio.models.wav2vec2_model(
extractor_mode: models.FeatureExtractorNormMode.group_norm,
extractor_conv_layer_config: new long[][] {
new long[] { 512, 10, 5 },
new long[] { 512, 3, 2 },
new long[] { 512, 3, 2 },
new long[] { 512, 3, 2 },
new long[] { 512, 3, 2 },
new long[] { 512, 2, 2 },
new long[] { 512, 2, 2 }
},
extractor_conv_bias: false,
encoder_embed_dim: 768,
encoder_projection_dropout: 0.1,
encoder_pos_conv_kernel: 128,
encoder_pos_conv_groups: 16,
encoder_num_layers: 12,
encoder_num_heads: 12,
encoder_attention_dropout: 0.1,
encoder_ff_interm_features: 3072,
encoder_ff_interm_dropout: 0.0,
encoder_dropout: 0.1,
encoder_layer_norm_first: false,
encoder_layer_drop: 0.05,
aux_num_out: 29);
model.eval(); …
```

Add Wav2Vec2 models

---

src/TorchSharp/TorchVision/models/ResNet.cs

Fix ResNet MaxPool2d kernel_size

---

src/TorchSharp/TorchVision/Ops.cs

This is a C# implementation of [NMS](https://pytorch.org/vision/0.9/ops.html?highlight=nms#torchvision.ops.nms), which is verified in object detection feature.

add non-maximum suppression (NMS) function to torchsharp

---

test/TorchSharpTest/TestTorchVisionOps.cs

add unittest of torchvision.ops.nms

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Bilinear.cs
src/TorchSharp/NN/Linear.cs
test/TorchSharpTest/NN.cs

Also changed bilinear to use native function directly.

Address issue #749 -- incorrect nn.functional.linear function signature.

---

src/TorchSharp/TorchVision/Ops.cs
src/TorchSharp/TorchVision/Ops/Misc.cs
src/TorchSharp/TorchVision/models/MobileNetV2.cs
src/TorchSharp/TorchVision/models/Utils.cs
test/TorchSharpTest/TestTorchVision.cs

https://pytorch.org/vision/stable/models/generated/torchvision.models.mobilenet_v2.html#torchvision.models.mobilenet_v2
Compatible with these state_dict's converted. https://github.com/dotnet/TorchSharp/issues/588
- https://download.pytorch.org/models/mobilenet_v2-7ebf99e0.pth
- https://download.pytorch.org/models/mobilenet_v2-b0353104.pth
The code is from main branch of torchvision that has difference from v0.12.0 (for PyTorch v1.11.0)

Add torchvision.models.mobilenet_v2()

---

src/TorchSharp/TorchVision/Ops/Misc.cs
src/TorchSharp/TorchVision/models/MobileNetV3.cs
test/TorchSharpTest/TestTorchVision.cs

https://github.com/dotnet/TorchSharp/issues/588 State-dict compatible with 
- https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth
- https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth
- https://download.pytorch.org/models/mobilenet_v3_large-8738ca79.pth

Add `torchvision.models.mobilenet_v3_large()` and torchvision.models.mobilenet_v3_small()`

---

src/TorchSharp/NN/Module.cs
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/LBFGS.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/Optimizer.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTraining.cs

Support saving and restoring optimizer state.

---

src/Examples.Utils/Datasets.cs
src/FSharp.Examples/AdversarialExampleGeneration.fs
src/FSharp.Examples/AlexNet.fs
src/FSharp.Examples/MNIST.fs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs
src/TorchSharp/NN/EmbeddingBag.cs
src/TorchSharp/NN/Pooling/MaxUnpool1d.cs
src/TorchSharp/NN/Pooling/MaxUnpool2d.cs
src/TorchSharp/NN/Pooling/MaxUnpool3d.cs
src/TorchSharp/NN/TransformerEncoder.cs
src/TorchSharp/NN/TransformerEncoderLayer.cs
src/TorchSharp/Torch.cs

Adding 'torch.cuda_is_available()' for use by F#.

Adding missing generics and interfaces to some Modules.

---

src/TorchSharp/Tensor/Tensor.torch.cs

Add default parameter for dim of torch.cat()

---

azure-pipelines.yml
src/TorchSharp/TorchSharp.csproj
src/TorchVision/IO/ImageFormat.cs
src/TorchVision/TorchVision.csproj

Moved SkiaSharp dependency to TorchVision

---

src/TorchSharp/ConsoleProgressBar.cs
src/TorchSharp/Hub.cs
src/TorchSharp/IProgressBar.cs
test/TorchSharpTest/TestTorchHub.cs

Fix #783
Tested on
- Ubuntu 22.04 via SSH over Windows Terminal
- Windows Terminal
- Windows command prompt
- Windows Jupyter Lab

`torch.hub.download_url_to_file()` supports progress bar

---

src/Native/LibTorchSharp/THSLoss.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Losses.cs

Addresses the one remaining item in #416

Added support for label smoothing in CrossEntropyLoss.

---

src/TorchSharp/NN/Activation/LogSoftMax.cs
src/TorchSharp/Special.cs
src/TorchSharp/Tensor/Tensor.Math.cs
test/TorchSharpTest/NN.cs

Adding unit test for CTCLoss.

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTorchTensor.cs

Added unit tests for squeeze_() and unsqueeze()

Adding squeeze_()

---

README.md
RELEASENOTES.md
TorchSharp.sln
src/TorchSharp/NN/Activation/ReLU6.cs
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

Adding a few factories for tensors -- IntTensor, FloatTensor, etc.

---

RELEASENOTES.md
src/TorchSharp/Distributions/Bernoulli.cs
src/TorchSharp/Distributions/Categorical.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Bug fixes related to distributions

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/NN/Dropout1d.cs
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSAutograd.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSLinalg.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSNN.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

Adding torch.linalg APIs from 1.12 and 1..13

1.12 and 1.13 torch.linalg APIs.

---

build/ci/job-template.yml

I'm basically shooting in the dark here, trying to get the right version of .NET Core installed.

More work on getting the right .NET version installed on the Widows VMs.

---

src/TorchSharp/NN/Module.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Fixes #845

---

RELEASENOTES.md
src/FSharp.Examples/FSharp.Examples.fsproj
src/TorchSharp/NN/Sequential.cs
test/TorchSharpTest/NN.cs

Issue #852

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

This learning rate scheduler was introduced in PyTorch 1.13.

PolynomialLR implemented

---

RELEASENOTES.md
azure-pipelines.yml
src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Distributions/Transforms.cs
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSLinalg.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

Adadelta 'maximize'
ldl_factor, ldl_solve
SoftplusTransform

Adding a few 1.12 APIs.

---

RELEASENOTES.md
src/TorchSharp/NN/Sequential.cs
test/TorchSharpTest/NN.cs

Support indexing of Sequential.

---

src/TorchSharp/Utils/TensorAccessor.cs
test/TorchSharpTest/TestTorchTensor.cs

Remove dimension limit

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSCuda.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
src/TorchSharp/Torch.cs
test/TorchSharpTest/TestDisposeScopes.cs
test/TorchSharpTest/TestTorchSharp.cs

Adding some backend properties, per issue #889.

Added some CUDA and CUDNN backend properties.

---

src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs

Not passing anything should result in nothing happening.

Fixed defaults for set_printoptions.

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSAutograd.cpp
src/Native/LibTorchSharp/THSAutograd.h
src/TorchSharp/Autograd.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSAutograd.cs
src/TorchSharp/Tensor/torch.LocallyDisablingGradientComputation.cs
test/TorchSharpTest/TestNNUtils.cs

Adding anomaly detection APIs to torch.autograd

---

RELEASENOTES.md
build/BranchInfo.props
src/Examples/Properties/launchSettings.json
src/Examples/VGG.cs
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Utils/NotebookFormattingSupport.cs

Also, fixed bug in all stateful optimizers that prevented state from properly moving to another device.

Improve Tensor string formatting in Notebooks.

---

RELEASENOTES.md
src/TorchSharp/Torch.cs

Fix to the issue with loading 'nvfuser_codegen.dll' on Windows.

---

RELEASENOTES.md
build/BranchInfo.props
src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Distributions/MultiVariateNormal.cs
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSLinalg.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/torch.OtherOperations.cs
test/TorchSharpTest/LinearAlgebra.cs
test/TorchSharpTest/TestDistributions.cs

Adding a few linear algebra methods.
Update release notes and version number.

Adding MultiVariateNormal to torch.distributions.

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/torch.RandomSampling.cs
src/TorchSharp/Tensor/torch.cs

Update version number and release notes.

Deprecated 'randperm_out'

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Transformer.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSNN.cs
test/TorchSharpTest/NN.cs

Implement scaled_dot_product_attention and unit test.

---

src/TorchSharp/Scalar.cs
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/PointwiseTensorMath.cs
test/TorchSharpTest/TestTorchTensor.cs

https://github.com/dotnet/TorchSharp/issues/1046

[Enhanced function] Issue #1046

---

README.md

https://github.com/ChengYen-Tang/TorchSharp/tree/contrib#developing-and-contributing

Just Beautiful Readme

---

RELEASENOTES.md

Updated releasenotes for save_image/make_grid and RandAugment

Updated releasenotes for save_image/make_grid and RandAugment

---

src/TorchVision/AutoAugment.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchVisionTransforms.cs

I wanted to use RandAugment from the pytorch autoaugment module. https://pytorch.org/vision/main/generated/torchvision.transforms.RandAugment.html
I think this is line for line equivalent to the pytorch code, but maybe needs additional improvements specific to TorchSharp. It works as expected, but depends on my previous PRs

Port RandAugment from pytorch

---

RELEASENOTES.md
build/BranchInfo.props
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchVisionTransforms.cs

The PR also picks up a pending change to a test file.

Disable a failing unit test.

---

src/TorchSharp/Torch.cs

don't init trace StringBuilder if backend already loaded

---

RELEASENOTES.md
src/TorchSharp/Device.cs
src/TorchSharp/Torch.cs
test/TorchSharpTest/PointwiseTensorMath.cs
test/TorchSharpTest/TestJIT.cs
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs

Disabled some unit tests that hang CI/CD builds when run concurrently.

Fixed issue related to not initializing CUDA before using it.

---

RELEASENOTES.md
src/TorchSharp/JIT/ScriptModule.cs
test/TorchSharpTest/TestJIT.cs

Also, adding the ability to add pre- and post-hooks (forward only)

Re-introduce `forward` to ScriptModule

---

RELEASENOTES.md
src/TorchSharp/NN/GenericSequential.cs
src/TorchSharp/NN/Sequential.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestNNUtils.cs

See discussion here:
https://github.com/dotnet/TorchSharp/issues/1112

Support derivation of Sequential modules with custom `forward` implementations and signatures.

---

RELEASENOTES.md
src/TorchSharp/Tensor/Tensor.Operators.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Address an API issue that affected F# only.

---

docfx/articles/saveload.md

I added a paragraph in the Wiki referencing the package. 
Please let me know if you want me to revise it in any way.

Added section in Save/Load readme for TorchSharp.PyBridge

---

test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestNormalize.cs

Here is the simple unit test I wrote, for LayerNorm. Not able to run this locally at this time, so no idea if it works. Please let me know if it works for you @NiklasGustafsson

Add unit test for LayerNorm

---

src/TorchSharp/Distributions/Beta.cs
src/TorchSharp/Distributions/Binomial.cs
src/TorchSharp/Distributions/Categorical.cs
src/TorchSharp/Distributions/Cauchy.cs
src/TorchSharp/Distributions/Dirichlet.cs
src/TorchSharp/Distributions/Distribution.cs
src/TorchSharp/Distributions/ExpRelaxedCategorical.cs
src/TorchSharp/Distributions/Exponential.cs
src/TorchSharp/Distributions/FisherSnedecor.cs
src/TorchSharp/Distributions/Gamma.cs
src/TorchSharp/Distributions/GumbEL.cs
src/TorchSharp/Distributions/Laplace.cs
src/TorchSharp/Distributions/LogitRelaxedBernoulli.cs
src/TorchSharp/Distributions/MultiVariateNormal.cs
src/TorchSharp/Distributions/Multinomial.cs
src/TorchSharp/Distributions/NegativeBinomial.cs
src/TorchSharp/Distributions/Normal.cs
src/TorchSharp/Distributions/OneHotCategorical.cs
src/TorchSharp/Distributions/Poisson.cs
src/TorchSharp/Distributions/TransformedDistribution.cs
src/TorchSharp/Distributions/Uniform.cs

Per request in #1158, adding IDisposable to all the distribution classes.

Added IDisposable to distribution classes.

---

src/TorchSharp/NN/Activation/PReLU.cs
src/TorchSharp/NN/Bilinear.cs
src/TorchSharp/NN/Convolution/Conv1D.cs
src/TorchSharp/NN/Convolution/Conv2D.cs
src/TorchSharp/NN/Convolution/Conv3D.cs
src/TorchSharp/NN/Convolution/ConvTranspose1D.cs
src/TorchSharp/NN/Convolution/ConvTranspose2D.cs
src/TorchSharp/NN/Convolution/ConvTranspose3D.cs
src/TorchSharp/NN/Embedding.cs
src/TorchSharp/NN/EmbeddingBag.cs
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/Normalization/BatchNorm1D.cs
src/TorchSharp/NN/Normalization/BatchNorm2D.cs
src/TorchSharp/NN/Normalization/BatchNorm3D.cs
src/TorchSharp/NN/Normalization/GroupNorm.cs
src/TorchSharp/NN/Normalization/InstanceNorm1d.cs
src/TorchSharp/NN/Normalization/InstanceNorm2d.cs
src/TorchSharp/NN/Normalization/InstanceNorm3d.cs
src/TorchSharp/NN/Recurrent/GRUCell.cs
src/TorchSharp/NN/Recurrent/LSTMCell.cs
src/TorchSharp/NN/Recurrent/RNNCell.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestNormalize.cs

Added null-argument validation to native-implementation NN modules with modifiable tensor properties.

Native module property argument validation

---

src/TorchSharp/Distributions/Bernoulli.cs
src/TorchSharp/Distributions/Beta.cs
src/TorchSharp/Distributions/Binomial.cs
src/TorchSharp/Distributions/Categorical.cs
src/TorchSharp/Distributions/Cauchy.cs
src/TorchSharp/Distributions/Dirichlet.cs
src/TorchSharp/Distributions/Distribution.cs
src/TorchSharp/Distributions/ExpRelaxedCategorical.cs
src/TorchSharp/Distributions/Exponential.cs
src/TorchSharp/Distributions/FisherSnedecor.cs
src/TorchSharp/Distributions/Gamma.cs
src/TorchSharp/Distributions/Geometric.cs
src/TorchSharp/Distributions/GumbEL.cs
src/TorchSharp/Distributions/Independent.cs
src/TorchSharp/Distributions/Kumaraswamy.cs
src/TorchSharp/Distributions/Laplace.cs
src/TorchSharp/Distributions/LogNormal.cs
src/TorchSharp/Distributions/LogitRelaxedBernoulli.cs
src/TorchSharp/Distributions/MultiVariateNormal.cs
src/TorchSharp/Distributions/Multinomial.cs
src/TorchSharp/Distributions/NegativeBinomial.cs
src/TorchSharp/Distributions/Normal.cs
src/TorchSharp/Distributions/OneHotCategorical.cs
src/TorchSharp/Distributions/Pareto.cs
src/TorchSharp/Distributions/Poisson.cs
src/TorchSharp/Distributions/RelaxedBernoulli.cs
src/TorchSharp/Distributions/RelaxedOneHotCategorical.cs
src/TorchSharp/Distributions/TransformedDistribution.cs
src/TorchSharp/Distributions/Uniform.cs
src/TorchSharp/Distributions/Weibull.cs

Fixed the Dispose() pattern.

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Normalization/LayerNorm.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

@shaltielshmid, @GilesBathgate -- please review.

Address #1185

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSJIT.cpp
src/Native/LibTorchSharp/THSJIT.h
src/TorchSharp/JIT/ScriptModule.cs
src/TorchSharp/NN/Upsample.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSJIT.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestJIT.cs

Also: add capability to load a script module from a byte array.

Address issue #1202.

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/torch.ReductionOps.cs
test/TorchSharpTest/TestTorchTensor.cs

Missing Tensor.prod() and torch.prod()

---

RELEASENOTES.md
build/BranchInfo.props

(I also put the bug fixes section below the api changes, as is in the rest of the file)

Updated release notes

---

src/Native/LibTorchSharp/THSAutograd.cpp
src/TorchSharp/AutogradFunction.cs
test/TorchSharpTest/TestAutogradFunction.cs

1] Moved to using safe handles, since all variables are expected to be present. 
2] Fixed backward return to allow null for variable inputs.

Adjusted custom autograd function

---

README.md

In PyTorch you don't have to dispose tensors
this tensors sits on memory and should be disposed

Update README.md Tensor disposing

---

RELEASENOTES.md
src/TorchSharp/Tensor/torch.ReductionOps.cs

make torch.unique and torch.unique_consecutive public

---

test/TorchSharpTest/TorchSharpTest.csproj

I have found out why [this](https://github.com/dotnet/TorchSharp/pull/1262#issuecomment-1998669584) was happening.

Modify LangVersion of TorchSharpTest

---

RELEASENOTES.md
src/TorchSharp/DataLoader.cs
src/TorchSharp/DisposeScope.cs
src/TorchSharp/DisposeScopeManager.cs
src/TorchSharp/Tensor/Tensor.cs

replace `assert`s in `RemoveDisposeScope`

---

Directory.Build.props
build/BranchInfo.props
pkg/Directory.Build.targets
src/Native/LibTorchSharp/CMakeLists.txt

Fixes #681 
I also fixed the native build which was broken for me on Windows with VS 17.11 / cmake 3.23.

Enable package validation

---

src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Fixed npstr() of empty tensor()

---

src/TorchSharp/NN/Activation/GELU.cs
src/TorchSharp/NN/Activation/Hardshrink.cs
src/TorchSharp/NN/Activation/Hardtanh.cs
src/TorchSharp/NN/Activation/Mish.cs
src/TorchSharp/NN/Activation/SiLU.cs
src/TorchSharp/NN/Activation/Sigmoid.cs
src/TorchSharp/NN/Activation/Softplus.cs
src/TorchSharp/NN/Activation/Softshrink.cs
src/TorchSharp/NN/Activation/Softsign.cs
src/TorchSharp/NN/Activation/Tanh.cs
src/TorchSharp/NN/Activation/Tanhshrink.cs
src/TorchSharp/NN/Activation/Threshold.cs
src/TorchSharp/NN/Convolution/Convolution.cs
src/TorchSharp/NN/FeatureDropout.cs
src/TorchSharp/NN/Normalization/NormBase.cs
src/TorchSharp/Tensor/Tensor.cs

Adjust to API compat errors in the previous PR.

Adapted to some API Compat complaints.
