TorchSharp/TypeGeneration.cs
TorchSharp/TypeGeneration.tt

Here's a question of mine: should the 'Masked' prefix be there for MaskedFill/Copy/Select, or is a shorter name better and let overloading take care of the disambiguation? If this is meant as a low-level API with high fidelity to the C interface, then I think they should be present, otherwise I would argue for letting overloading take care of it.

Adding support for a couple of tensor ops.

---

Directory.Build.props
README.md
azure-pipelines.yml
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/TorchSharp/JIT/Type/TensorType.cs
src/TorchSharp/PinnedArray.cs
src/TorchSharp/Scalar.cs
src/TorchSharp/Tensor/Half.cs
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/Tensor/Types.ttinclude
test/TorchSharpTest/TorchSharp.cs

* Add half-precision floating point tensor support (currently using a TorchSharp.Half type for in/out creation).
* Add Torch 1.5.0 Bool/Byte tensor support 
* Add maxpool_with_indices and friends
* Add scatter/gather
* Rename ATenScalarMapping to ScalarType

Fix Torch 1.5.0 Bool/Byte tensor support and add other functionality

---

src/Native/LibTorchSharp/THSTensor.cpp
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt

@gbaydin requested these ops in #140 
In some cases (for the distributions) only the inplace versions of the ops appear to be available in the C++ API.

Add the ops needed for DiffSharp

---

Directory.Build.targets
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Torch.cs
src/TorchSharp/TorchSharp.csproj
test/TorchSharpTest/TorchTensor.cs

This fixes #159 
Note that TorchSharp is now `netcoreapp3.0` in order to use the relevent API to load native components accurately

Fix DLL loading on Windows

---

DEVGUIDE.md
README.md
docfx/articles/memory.md
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TorchSharp.cs
test/TorchSharpTest/TorchSharpTest.csproj
test/TorchSharpTest/TorchTensor.cs

Partially addresses #167 
Three approaches are available for memory management.
- If having trouble with GPU memory you may have to resort to technique 1.
- If having trouble with CPU memory you may have to resort to technique 3, else 1.
DiffSharp relied on technique 2 and 3.
In this technique specific tensors (CPU and GPU) are explicitly disposed
using `using` in C# or explicit calls to `System.IDisposable.Dispose()`.
👍 control
👎 you must know when to dispose
> NOTE: Disposing a tensor only releases the underlying storage if this is the last
> live TorchTensor which has a view on that tensor.
In this technique all tensors (CPU and GPU) are implicitly disposed via .NET finalizers.
👍 Simple
👎 The .NET GC doesn't know of the memory pressure from CPU tensors, so failure may happen if large …

Add explicit memory pressure option for tensors

---

src/Native/LibTorchSharp/Utils.cpp
src/Native/LibTorchSharp/Utils.h
src/TorchSharp/NN/AdaptiveAvgPool2D.cs
src/TorchSharp/NN/AvgPool2D.cs
src/TorchSharp/NN/Conv2D.cs
src/TorchSharp/NN/Dropout.cs
src/TorchSharp/NN/FeatureDropout.cs
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/LogSoftMax.cs
src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/MaxPool2D.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/NN/ReLu.cs
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt

We were always doing a pinvoke to check for errors, but nearly all the time it can be avoided

avoid unnecessary p/invoke calls

---

DEVGUIDE.md
Directory.Build.props
azure-pipelines.yml
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Redist/libtorch-cuda-10.2/libtorch-cuda-10.2.proj
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TestTorchTensor.cs

The ScalarDiv, ScalarSub and ScalarRemainder ops have to direct LibTorch equivalent AFAICS, at least not as they are written.  Furthermore they are buggy with integral types

rm scalar ops

---

README.md
build/Codecoverage.proj
docfx/articles/memory.md
init-tools.sh
pkg/TorchSharp/TorchSharp.nupkgproj
src/Examples/AlexNet.cs
src/Examples/Examples.csproj
src/Examples/MNIST.cs
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTorch.cpp
src/Native/LibTorchSharp/THSTorch.h
src/Redist/libtorch-cpu/libtorch-cpu.proj
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
src/TorchSharp/Tensor/Types.ttinclude
src/TorchSharp/Torch.cs
src/TorchSharp/TorchScalar.cs
src/TorchSharp/TorchSharp.csproj
test/Directory.Build.props
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TorchSharpTest.csproj

Now we've upgraded to LibTorch 1.7.0 we can get further with bfloat16, float16 support
These are only supported on GPU
This also includes some renaming to give better code clarity now these are supported, e.g. `Int64Tensor` instead of `LongTensor`

bfloat16, float16 testing and functionality

---

README.md
azure-pipelines.yml
build/BranchInfo.props
src/Examples/AlexNet.cs
src/Examples/MNIST.cs
src/Native/LibTorchSharp/THSJIT.h
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/JIT/Module.cs
src/TorchSharp/NN/AdaptiveAvgPool2D.cs
src/TorchSharp/NN/AvgPool2D.cs
src/TorchSharp/NN/Conv2D.cs
src/TorchSharp/NN/Dropout.cs
src/TorchSharp/NN/FeatureDropout.cs
src/TorchSharp/NN/Init.cs
src/TorchSharp/NN/Linear.cs
src/TorchSharp/NN/LogSoftMax.cs
src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/MaxPool2D.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/NN/Parameter.cs
src/TorchSharp/NN/ReLu.cs
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs

Implements the renaming discused in https://github.com/xamarin/TorchSharp/issues/95 to match SciSharp conventions.
This aligns TorchSharp with the conentions and methodology of TensorFlow.NET which is used in ML.NET.
There are pros and cons to this, but as TorchSharp is adding no specific semantics over PyTorch, it simplifies a lot of things along education paths to adopt PyTorch namings.

renaming to match SciSharp

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Optimizer.cs
test/TorchSharpTest/NN.cs

Prior to this PR, not all optimizer hyperparameters were available to the .NET client code. This adds all parameters and implements any defaulting on the .NET side.

Allow all the optimizer parameters to be passed explicitly

---

Directory.Build.targets
src/TorchSharp/Torch.cs

This extends our current unsatisfactory workaround for problems with libtorch dynamic linking described in #212 
I think the problem is really with libtorch, and until we know what else to do this is adequate

add cudnn_ops_train64 etc to preload list for Windows

---

src/Examples/AlexNet.cs
src/Examples/MNIST.cs
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Conv1D.cs
src/TorchSharp/NN/Conv2D.cs
src/TorchSharp/NN/Conv3D.cs
src/TorchSharp/NN/ConvTranspose1D.cs
src/TorchSharp/NN/ConvTranspose2D.cs
src/TorchSharp/NN/ConvTranspose3D.cs
src/TorchSharp/NN/Embedding.cs
src/TorchSharp/NN/Identity.cs
src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/OneHot.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/NN.cs

Added:
-  a number of the most common loss functions.
- one-hot encoding
- Embedding module
Moved the loss functions to the 'Functions' static class, since there's no 'nn.losses' in PyTorch.

Loss functions

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
test/TorchSharpTest/TestTorchTensor.cs

I started adding documentation comments to existing code. Not done by a long shot, but it's a start.
I snuck in a couple of API changes; a) allow tensors to be moved to another device and recast to another type in one operation, which the Python 'to()' function allows, and b) support indexing tensors with TorchTensorIndex using the '[]' syntax.

Adding documentation comments

---

src/TorchSharp/NN/Module.cs

Each .NET Module instance potentially has two handles to the native module. Both of them have to be released when the instance is disposed.
Fixes #233.

Fixing native code memory leak.

---

src/Examples/AlexNet.cs
src/Examples/MNIST.cs
src/TorchSharp/NN/Convolution/Conv1D.cs
src/TorchSharp/NN/Convolution/Conv2D.cs
src/TorchSharp/NN/Convolution/Conv3D.cs
src/TorchSharp/NN/Convolution/ConvTranspose1D.cs
src/TorchSharp/NN/Convolution/ConvTranspose2D.cs
src/TorchSharp/NN/Convolution/ConvTranspose3D.cs
src/TorchSharp/NN/Normalization/BatchNorm1D.cs
src/TorchSharp/NN/Normalization/BatchNorm2D.cs
src/TorchSharp/NN/Normalization/BatchNorm3D.cs
src/TorchSharp/NN/Normalization/InstanceNorm1d.cs
src/TorchSharp/NN/Normalization/InstanceNorm2d.cs
src/TorchSharp/NN/Normalization/InstanceNorm3d.cs
src/TorchSharp/NN/Pooling/AdaptiveAvgPool1D.cs
src/TorchSharp/NN/Pooling/AdaptiveAvgPool2D.cs
src/TorchSharp/NN/Pooling/AdaptiveAvgPool3D.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool1D.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool2D.cs
src/TorchSharp/NN/Pooling/AdaptiveMaxPool3D.cs
src/TorchSharp/NN/Pooling/AvgPool1D.cs
src/TorchSharp/NN/Pooling/AvgPool2D.cs
src/TorchSharp/NN/Pooling/AvgPool3D.cs
src/TorchSharp/NN/Pooling/MaxPool1D.cs
src/TorchSharp/NN/Pooling/MaxPool2D.cs
src/TorchSharp/NN/Pooling/MaxPool3D.cs
test/TorchSharpTest/TestLoadSave.cs

Renamed 1D/2D/3D -> 1d/2d/3d to correspond with how layers are named in the Python and C++ APIs.
The code I recently added adhered to the few layers already in existence, which used 'D" instead of 'd' like the Python APIs do. This PR corrects that, so that the APIs look more like the ones available in Python.

Renamed 1D/2D/3D -> 1d/2d/3d

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs

This starts the implementation of the 'torch.linalg' namespace. Not all of the Python operations are available in the C++ library that we currently depend on, so only the ones that are have been implemented.

Adding the linalg namespace, and most of its operations.

---

src/Examples/SequenceToSequence.cs
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/EmbeddingBag.cs
test/TorchSharpTest/NN.cs

Adding EmbeddingBag module, and fixing the seq2seq example -- with GC.Collect() between every batch, there is no need for all the usings.

Examples: Seq-to-Seq using a Transformer.

---

src/TorchSharp/Tensor/TorchTensor.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Instead of returning an invalid native pointer when data lives off-CPU, which will cause all kinds of havoc, throw a .NET exception as a preventative measure.
Fixes issue #145

Fixed issue #145

---

src/Native/LibTorchSharp/CMakeLists.txt
src/Native/LibTorchSharp/THSFFT.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/TorchTensor.FFT.cs
src/TorchSharp/Tensor/TorchTensor.Math.cs
src/TorchSharp/Tensor/TorchTensor.Trig.cs
src/TorchSharp/Tensor/TorchTensorTyped.generated.cs
src/TorchSharp/Tensor/TorchTensorTyped.tt
test/TorchSharpTest/TestTorchTensor.cs

This PR adds the operations from the 1.8 torch::fft namespace, which is useful for signal processing.
Also adding a few unit tests for complex abs and angle computation (useful for conversion to polar representation).

Adding torch::fft operations.

---

Directory.Build.props
azure-pipelines.yml

This should in theory create libtorch cpu Mac packages one merged into master.  
The Linux and Windows pacakges libtorch CPU and CUDA will also be built with version bump to 1.8.0.8

build libtorch cpu mac packages

---

azure-pipelines.yml

We do our linux builds on Ubuntu 16.04 containers to get Linux binaries that have very low dependency levels, hence usable in environments like Google Colab notebooks.
Ubuntu 16.04 vmImages are being retired, however the 16.04 containers we use should be able to run on `ubuntu-latest`

Use ubuntu-latest to hold ubuntu 16-04 containers

---

pkg/common/RestitchPackage.targets
src/Redist/libtorch-cuda-11.1/libtorch-cuda-11.1.proj

So LibTorch now contains single binaries with size > Int32.MaxValue.  😱 😱 😱 😱

allow splitting files size > int32 max

---

src/TorchSharp/NN/Losses.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Optimizer.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

This PR fixes three instances of native tensor handles being freed more than once, causing access violations.
It includes the fix surfaced in PR #316.

Fixes for double-freeing native tensor handles.

---

.gitignore
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/Utils.h
src/TorchSharp/NN/MultiheadAttention.cs
test/TorchSharpTest/NN.cs

We need the MultiheadAttention module by itself for some types of models. 
Although MultiheadAttention is part of the transformer modules, it is also needed separately (i.e. outside of transformer) for some models.

Include MultiheadAttention module in C# API

---

src/TorchSharp/Distributions/Dirichlet.cs
src/TorchSharp/Distributions/Poisson.cs

`xlogy` is more numerically stable than explicit maths.
See https://github.com/pytorch/pytorch/blob/f596aa8b77d6c57dd82f33a45926fad95ab2a21e/torch/distributions/poisson.py#L63 for example.

Use xlogy instead of y.log()*x for log_prob in Dirichlet and Poisson

---

src/Examples/MobileNet.cs
src/Examples/ResNet.cs

* Replace "MobileNet" with "ResNet" for ResNet implementation's Doc.
* Remove Remarks for MobileNet and ResNet
Hi @NiklasGustafsson, I removed the remarks from these files because it looks to me that they were copied from the VGG file (based on this [commit](https://github.com/dotnet/TorchSharp/commit/bf29b30ea4cf9917b9bf70f9674b0b010672e93c)) which later got upated [here](https://github.com/dotnet/TorchSharp/commit/25d32343ee929b828ad1c678ca60768a4489dde8). Please let me know if you wish to keep the remark sections.

Fix Net docs

---

README.md
azure-pipelines.yml

The Linux builds were failing because Ubuntu 16.04 did not support OpenSSL 1.1. Upgrading builds to 18.04.

Linux patch

---

RELEASENOTES.md
build/BranchInfo.props
docfx/articles/saveload.md
src/Examples/ImageTransforms.cs
src/Examples/SequenceToSequence.cs
src/Examples/TextClassification.cs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Losses.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/TorchVision/ColorJitter.cs
src/TorchSharp/TorchVision/Functional.cs
src/TorchSharp/TorchVision/RandomChoice.cs
src/TorchSharp/TorchVision/RandomPerspective.cs
src/TorchSharp/TorchVision/Randomizer.cs
src/TorchSharp/Utils/TensorAccessor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestDistributions.cs
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Addresses bug #399 by supporting non-contiguous tensors, and #398 by renaming Data<T> and DataItem<T>

Implement Data<T> in a way that supports non-contiguous tensors.

---

src/TorchSharp/NN/Sequential.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestLoadSave.cs

In pytorch, there are two ways for declare sequential.
```
model = nn.Sequential(
nn.Conv2d(1,20,5),
nn.ReLU(),
nn.Conv2d(20,64,5),
nn.ReLU()
)
model = nn.Sequential(OrderedDict([
('conv1', nn.Conv2d(1,20,5)),
('relu1', nn.ReLU()),
('conv2', nn.Conv2d(20,64,5)),
('relu2', nn.ReLU())
]))
```
But torchsharp only has second way. So I added first way.
```cs
var model = nn.Sequential(
nn.Conv2d(1, 20, 5),
nn.ReLU(),
nn.Conv2d(20, 64, 5),
nn.ReLU()
);
```
This works same with first python code.
In my commit, when using first way, It will set name by type name of module. And I add test for new sequential(Save and loading, nn in sequential)
I think `using torch.torchvision` in #433 was just mistake :D
Thanks for NiklasGustafsson, he(or she) helped me for solving that my commit has crushing on F#, …

 Make able to declare sequential without name of module 

---

src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Sequential.cs
test/TorchSharpTest/NN.cs

Addresses issue #439 concerning the names given to sub-modules of Sequential.
Also, Sequential should call Dispose on all sub-modules in order to free up native memory.

Correcting names of Sequential submodules

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

The purpose of these static properties is to help diagnosing memory management issues. The TotalCount property can be used to monitor the stability of the number of allocated tensors, which should remain steady across training epochs.

Adding Tensor.TotalCount and Tensor.PeakCount

---

RELEASENOTES.md
build/BranchInfo.props
src/Native/LibTorchSharp/THSRandom.cpp
src/Native/LibTorchSharp/THSVision.cpp
src/Native/LibTorchSharp/THSVision.h
src/TorchSharp/LinearAlgebra.cs
src/TorchSharp/NN/Functional.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Optimizer.cs
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.LinearAlgebra.cs
src/TorchSharp/Tensor/Tensor.Math.cs
src/TorchSharp/Tensor/Tensor.Trig.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
src/TorchSharp/TorchVision/Functional.cs
src/TorchSharp/TorchVision/ResizedCrop.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTraining.cs

I found a whole slew of torchvision functions that did not properly dispose of temporaries. The same problem was found in a number of the optimizers whose step() functions are written in .NET rather than native code.
In the process of fixing that issue, I also moved a number of the algorithms to native code, implementing them in C++ to avoid the interop overhead and the overhead of creating and disposing of short-lived .NET tensor aliases.
Also -- addressed an infinite recursion problem in a couple of the randint() overloads.

Torchvision memory management

---

src/Native/CMakeLists.txt

For faster native compilation.

Add /MP switch to WIN32 build in CMakeLists.txt

---

src/Native/LibTorchSharp/THSConvolution.cpp
test/TorchSharpTest/TestTorchTensorBugs.cs

The C++ code for Conv2d and Conv3d were incorrectly receiving the encoding of padding='same' and padding='valid'

Fixed issue #496

---

src/TorchSharp/Tensor/Tensor.Factories.cs

https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint
P.S. does not actually seem to be affected by `torch.set_default_tensor_type`, the default returned type is `int64` regardless.

Default dtype for torch.randint is int64

---

src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTensorMath.cpp
src/TorchSharp/Tensor/Tensor.Math.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestTorchTensor.cs

This is a straight-forward edit: just adding a few Tensor methods related to conjugates.

Adding support for Tensor.conj() and related functions.

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs

`Tensor` `int`-based indexers forced `AsScalar()` call on new values, which prevented assigning tensor slices.
fixes https://github.com/dotnet/TorchSharp/issues/521

Fixed assigning slice with integer indices

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Torch.cs

This should fix https://github.com/DiffSharp/DiffSharp/issues/387

fix package loading of TorchSharp-cpu from F#/.NET Interactive

---

test/Directory.Build.props
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestDataLoader.cs
test/TorchSharpTest/TestDisposeScopes.cs
test/TorchSharpTest/TestDistributions.cs
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchSharp.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs
test/TorchSharpTest/TorchSharpTest.csproj

This change is to re-enable the optimization option on the tests when running with NETFX 4.7.2. The change here is to serialize the test execution. This solves the issue of the crashing the test host and avoid the conflict between different tests.
https://github.com/dotnet/TorchSharp/issues/546
https://github.com/dotnet/TorchSharp/pull/543

Re-enable Optimization on test runs with NetFX 4.7.2

---

src/TorchSharp/NN/Recurrent/GRU.cs
src/TorchSharp/NN/Recurrent/LSTM.cs
src/TorchSharp/NN/Recurrent/RNN.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

The GRU, LSTM and RNN would create cpu weights if no weights were provided. Now the device of the input is used instead.
Also fixed issues where number formatting was missing - failing tests on machines with different string formatting settings.

Fixed GRU, LSTM and RNN to honor the device

---

RELEASENOTES.md
src/Examples/CIFAR10.cs
src/Examples/ResNet.cs
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSNormalization.cpp
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/Normalization/GroupNorm.cs
src/TorchSharp/NN/Sequential.cs
src/TorchSharp/Tensor/Storage.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
src/TorchSharp/TorchSharp.csproj
src/TorchSharp/TorchVision/models/AlexNet.cs
src/TorchSharp/TorchVision/models/ResNet.cs
src/TorchSharp/TorchVision/models/VGG.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchVision.cs

I added ResNet to torchvision.models. There's no direct support for pretrained weights, we'll need a place to store binary data that isn't in the repo itself, but for now, I'd appreciate comments on the UX.
I also added a 'skip' list to Module.load/save, which could be useful for not loading weights for some modules in a model, for example a last linear layer that will be replaced or has a different shape. 
Primary usage: transfer-learning.
Note that to skip a layer, all the state related to it must be skipped. For example, for a linear layer, both the 'weight' and 'bias,' if present, must be skipped.
With the new API, it should be possible to load a ResNet model that has a different number of classes from the one for which trained weights are available, simply by passing in 'fc.weight' …

Started on torchvision.models.

---

src/TorchSharp/Tensor/Tensor.Factories.cs
test/TorchSharpTest/TestTorchTensor.cs

adding a factory method for creating a tensor from an arbitrary array type. 
*Issues*
- some data types are not supported yet, since the appropriate factory methods are missing
- method is not named `tensor`, since the compiler cannot differentiate with the `tensor(IList<> ...)` methods in some cases when given the same name (ie. when the first parameter is of type `List<T>`)
- unit tests are missing, since i was unable to compile the project on my computer (insufficient disk space for the CUDA libs)

adding tensor factory for arbitrary arrays

---

src/TorchSharp/Tensor/Tensor.cs

* documenting the standard deviation function (`std`)
* providing an additional overload that doesn't require an array of dimensions

documenting std and providing additional overload

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/TestTorchTensor.cs

Adding Tensor.roll and torch.roll #621

---

src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs

This don't make change about t.str() but it will be useful for who wants to get Metadata string and Numpy style string.
I think `t.npstr()` is better then `t.str(TensorStringStyle.Numpy)`.

Add xxxstr() methods

---

src/Examples/Program.cs
src/Examples/SpeechCommands.cs

This model achieves around 60-70% accuracy which is similar to PyTorch version. However, it depends on `torchaudio.transform.Resample()` which is not available in TorchSharp yet.

Added SpeechCommands example

---

src/TorchSharp/Hub.cs

Fixes #657 
Similar issue with https://stackoverflow.com/questions/18720435/httpclient-buffer-size-limit-exceeded

`torch.hub.download_url_to_file()` fails to download a file > 2GB

---

src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSNN.h
src/TorchSharp/NN/Recurrent/GRU.cs
src/TorchSharp/NN/Recurrent/LSTM.cs
src/TorchSharp/NN/Recurrent/RNN.cs
src/TorchSharp/NN/Utils/PackedSequence.cs
test/TorchSharpTest/NN.cs

- RNN, LSTM, GRU accept `PackedSequence`
- PackedSequence.data, batch_sizes, sorted_indices, unsorted_indices added
- Fixed: RNN, LSTM, GRU fail to process float64 tensors.

RNN, LSTM, GRU support `PackedSequence`

---

src/TorchSharp/Tensor/Tensor.cs

following changes where made: 
- fixing nullable declaration on `clip` (an alias for `clamp`)
- making `quantile` and `nonquantile` methods public, such that they can be called by the user

fixing clamp and (non)quantile method declarations

---

src/TorchSharp/NN/Utils/RNNUtils.cs
src/TorchSharp/TorchAudio/Models.cs
src/TorchSharp/TorchAudio/Modules/Tacotron2.cs
test/TorchSharpTest/TestTorchAudioModels.cs

Added Tacotron2 implementation from https://github.com/pytorch/audio/blob/e502df0106403f7666f89fee09715256ea2e0df3/torchaudio/models/tacotron2.py
The file has a LICENSE notice from NVIDIA.
PyTorch has four pretrained mode
- char based Griffin-Lim
- char based WaveRNN
- phoneme based Griffin-Lim
- phoneme based WaveRNN
Quality of Griffin-Lim is not as good as WaveRNN. Phoneme based requires [DeepPhonemizer](https://github.com/as-ideas/DeepPhonemizer/) to process texts which is written with PyTorch.
One of pretrained models from PyTorch converted to TorchSharp.
`tacotron2_english_phonemes_1500_epochs_wavernn_ljspeech.pth`
https://drive.google.com/file/d/11TnhmCSUy7aO1pv9CBi7Qivhz25nl_2l/view?usp=sharing

Added `torchaudio.models.Tacotron2()`

---

pkg/FileRestitcher/FileRestitcher.Tests/FileRestitcher.Tests.csproj
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TorchSharpTest.csproj

As proposed in #615, now that xUnit version 2.4.2 has been released, we're upgrading so that we can assert more than one thing at a time, catching multiple failures.
Rather than spend energy on converting all unit tests to take advantage of this, I have converted half a handful, as an example. Look for Assert.Multiple() in the source code. Going forward, unit test writers are encouraged to organized assertions such that they take advantage of this new capability.

Update test projects to xUnit 2.4.2

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSFFT.cpp
src/Native/LibTorchSharp/THSTensor.h
src/Native/LibTorchSharp/THSTensorFactories.cpp
src/TorchSharp/FFT.cs
src/TorchSharp/Tensor/Tensor.Factories.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Per discussion in #670, the following will be how to create a tensor from arrays, aligned with Pytorch, treating `from_array()` as the equivalent of `from_numpy()`:
```C#
// Never copy:
public static Tensor from_array(Array rawArray)
// Copy if necessary:
public static Tensor frombuffer(Array rawArray, ScalarType dtype, long count = -1, long offset = 0, bool requiresGrad = false, Device? device = null)
public static Tensor as_tensor(Array data, ScalarType? dtype = null, Device? device = null)
public static Tensor as_tensor(Tensor data, ScalarType? dtype = null, Device? device = null)
// Always copy:
public static Tensor tensor(<<VARIOUS>>, torch.Device? device = null, bool requiresGrad = false)
```
This PR also addresses #679.

Rationalize how tensors are created from arrays.

---

src/TorchSharp/Tensor/Tensor.Math.cs
test/TorchSharpTest/TestTorchTensor.cs

This pull request contains the following changes:
- marking unit tests with `[TestOfAttribute]` in order to indicate the method under test
- small code cleanup of unit tests
- fixing a typo (`matric_exp` => `matrix_exp`) and marking the original version as obsolete

applying TestOfAttribute to unit tests 

---

src/TorchSharp/TorchAudio/Functional.cs
src/TorchSharp/TorchAudio/MelNorm.cs
src/TorchSharp/TorchAudio/MelScale.cs
test/TorchSharpTest/TestTorchAudio.cs

- torchaudio.functional.griffinlim()
- torchaudio.functional.amplitude_to_DB()
- torchaudio.functional.DB_to_amplitude()
- torchaudio.functional.melscale_fbanks()
- torchaudio.functional.linear_fbanks()

Added missing functions of `torchaudio.functional`

---

src/Native/LibTorchSharp/THSAutograd.cpp
src/Native/LibTorchSharp/THSAutograd.h
src/TorchSharp/Autograd.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestNNUtils.cs

Adding autograd.backward and unit tests.

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
src/TorchSharp/TorchAudio/Functional.cs
src/TorchSharp/TorchAudio/Modules/Tacotron2.cs
src/TorchSharp/TorchAudio/Transforms.cs
src/TorchSharp/TorchVision/Functional.cs
test/TorchSharpTest/TestTorchTensor.cs

- Add `repeat_interleave()`
- Add static function for `all()`, `any()`, `tile()`, `repeat_interleave()`.
- Fix comments
- Update the arguments of `dropout()` in `Tacotron2`

Add `Tensor.repeat_interleave()` and other functions

---

src/TorchSharp/TorchAudio/DCTNorm.cs
src/TorchSharp/TorchAudio/Functional.cs
test/TorchSharpTest/TestTorchAudio.cs

- `torchaudio.functional.create_dct()`
- `torchaudio.functional.mu_law_encoding()`
- `torchaudio.functional.mu_law_decoding()`

Add DCT and u-law of torchaudio

---

src/TorchSharp/TorchAudio/Models.cs
src/TorchSharp/TorchAudio/Modules/WaveRNN.cs
test/TorchSharpTest/TestTorchAudioModels.cs

As we don't have `torchaudio.pipelines` to download pretrained models, we need to manually do it.
```csharp
private static void Test()
{
var tacotron2 = torchaudio.models.Tacotron2(
mask_padding: false,
n_mels: 80,
n_frames_per_step: 1,
symbol_embedding_dim: 512,
encoder_embedding_dim: 512,
encoder_n_convolution: 3,
encoder_kernel_size: 5,
decoder_rnn_dim: 1024,
decoder_max_step: 2000,
decoder_dropout: 0.1,
decoder_early_stopping: true,
attention_rnn_dim: 1024,
attention_hidden_dim: 128,
attention_location_n_filter: 32,
attention_location_kernel_size: 31,
attention_dropout: 0.1,
prenet_dim: 256,
postnet_n_convolution: 5,
postnet_kernel_size: 5,
postnet_embedding_dim: 512,
gate_threshold: 0.5,
n_symbol: 96);
var path = Path.Combine(TORCH_HOME, …
```

Add `torchaudio.models.WaveRNN()`.

---

src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSNormalization.cpp
src/TorchSharp/NN/Normalization/Functional.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/Tensor.torch.cs
test/TorchSharpTest/NN.cs

- torch.nn.functional.batch_norm
- torch.nn.functional.group_norm
- torch.nn.functional.instance_norm
- torch.nn.functional.layer_norm
- torch.nn.functional.local_response_norm

Add functional normalizations

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchVisionOps.cs

This PR allows you to set the default tensor string format using `torch.TensorStringStyle = ...`

Added modifiable global default for tensor string formatting.

---

src/TorchSharp/NN/Activation/GLU.cs
src/TorchSharp/NN/Activation/Hardsigmoid.cs
src/TorchSharp/NN/Activation/Hardswish.cs
src/TorchSharp/NN/Activation/LeakyReLU.cs
src/TorchSharp/NN/Shuffle/ChannelShuffle.cs
test/TorchSharpTest/NN.cs

- Add torch.nn.Hardswish() and torch.nn.functional.hardswish()
- `torch.nn.functional.glu(): fix type of `dim`.
- `torch.nn.functional.hardsigmoid(): Call Tensor.hardsigmoid directly.
- `torch.nn.functional.hardsigmoid(): Uncapitalize function name
- `torch.nn.functional.leaky_relu(): Wrong default value of negative_slope. https://pytorch.org/docs/stable/generated/torch.nn.functional.leaky_relu.html#torch.nn.functional.leaky_relu
- `ChannelShuffle.cs` moved as it is not an activation function.

Add `torch.nn.Hardswish()` and `torch.nn.functional.hardswish()`

---

src/TorchSharp/Utils/tensorboard/SummaryWriter.cs
test/TorchSharpTest/TestLoadSave.cs

Also, fixed float comparison for equality -- always a no-no.

Fixed issues related to SummaryWriter wall time arguments.

---

RELEASENOTES.md
src/Examples/AdversarialExampleGeneration.cs
src/Examples/CIFAR10.cs
src/Examples/MNIST.cs
src/Examples/SequenceToSequence.cs
src/Examples/SpeechCommands.cs
src/Examples/TextClassification.cs
src/FSharp.Examples/AdversarialExampleGeneration.fs
src/FSharp.Examples/AlexNet.fs
src/FSharp.Examples/MNIST.fs
src/FSharp.Examples/SequenceToSequence.fs
src/FSharp.Examples/TextClassification.fs
src/Native/LibTorchSharp/THSLoss.cpp
src/TorchSharp/NN/Losses.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestLoadSave.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

The most immediate consequence is that losses are modules rather than delegates, which means you need to call `.forward()` to actually compute the loss. Also, the factories are in `torch.nn` rather than `torch.nn.functional` and have the same Pascal-casing as the corresponding types.
The members of the `torch.nn.functional` static class are now proper immediate loss functions, whereas the previous ones returned a loss delegate.

Align loss functions with PyTorch's APIs.

---

DEVGUIDE.md
README.md
RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Tensor/Tensor.Factories.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

The unit test is only meant not to verify that there is no compile-time error.

Adding 1-d array overloads for 'as_tensor()'

---

src/TorchSharp/NN/Module.cs

add_module API

---

RELEASENOTES.md
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/ModuleList.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/torch.OtherOperations.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Tensor.requires_grad_ ignored the argument passed.
Tensor.softmax (not documented in PyTorch docs) added.
Adding Module.modules() and Module.buffers()
Fixed ModuleList<T> factory method, which ignored all the input modules.

Fixed a couple of bugs.

---

src/Native/LibTorchSharp/THSLinearAlgebra.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/PInvoke/LibTorchSharp.THSLinalg.cs
src/TorchSharp/Tensor/Tensor.LinearAlgebra.cs
src/TorchSharp/Tensor/torch.OtherOperations.cs
test/TorchSharpTest/LinearAlgebra.cs

- removing unused `using` and prefixes in unit tests
- removing unused `torch.` prefixes in unit tests
- removing redundant `;` at the end of the `CATCH` and `CATCHTENSOR` macros
- implementing `tensordot`
my local build is not working
```cmd
dotnet build /p:SkipCuda=true /p:SkipNetFxBuild=true -c Debug
```
returns
```
Build FAILED.
CMake Error : error : generator : Visual Studio 17 2022 [C:\Users\movgp\TorchSharp\src\Native\build.proj]
C:\Users\movgp\TorchSharp\src\Native\build.proj(53,5): error MSB3073: The command ""C:\Users\movgp\TorchSharp\src\Native\build.cmd" Debug x64 --libtorchpath
C:\Users\movgp\TorchSharp\bin/obj/AnyCPU.Debug\libtorch-cpu\libtorch-win-shared-with-deps-debug-1.13.0cpu\libtorch\share\cmake\Torch" exited with code -1.
0 Warning(s)
2 Error(s)
```
Using this pull …

implementing torch.tensordot and some code cleanup

---

src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/torch.ComparisonOps.cs
test/TorchSharpTest/TestTorchTensor.cs

Add torch.histogram

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Tensor/torch.IndexingSlicingJoiningMutatingOps.cs

There was a second version of `torch.squeeze()` with incorrect default arguments. It has now been removed.

Fix torch.squeeze issue.

---

RELEASENOTES.md
build/BranchInfo.props
pkg/Directory.Build.props

This apparently the preferred way for NuGet packages.

Updated the NuGet metadata to use a license expression rather than a reference to a license file.

---

src/TorchVision/Grayscale.cs

TorchSharp `Greyscale()` transform assumes batch dimension when calculating the channel dim `channel = image.shape[1]` but this is not correct, as for a non-batched tensor `channel = image.shape[0]` The channel dim should be calculated using something such as  `channel = image.shape[image.ndim - 3]`
Example working pytorch:
```python
img = torch.rand((1, 32, 32))
result = torchvision.transforms.functional.rgb_to_grayscale(img)
result = torchvision.transforms.Grayscale()(img)
```
Example failing Torchsharp
```c#
var img = torch.rand(1, 32, 32);
var res = torchvision.transforms.functional.rgb_to_grayscale(img);
var res2 = torchvision.transforms.Grayscale().call(img);
```

Fix exception in Grayscale.cs

---

src/Native/LibTorchSharp/THSVision.cpp

This should suppress the warning in #1049

Suppress warning by setting align_corners false

---

src/Native/LibTorchSharp/THSTorch.cpp
src/TorchSharp/PInvoke/LibTorchSharp.THSCuda.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSTorchCuda.cs
src/TorchSharp/Torch.cs
test/TorchSharpTest/TestTorchSharp.cs

The native function binding for `torch.cuda.synchronize` had a mismatched name, which resulted in a link error at runtime when the symbol could not be found. This commit fixes that by renaming the native binding in C# (from `THSCuda_synchronize`) to `THSTorchCuda_synchronize` as defined in the associated header file.

Fix cuda synchronize method

---

src/TorchVision/Functional.cs
test/TorchSharpTest/TestTorchVision.cs

The `Blend()` function in `TorchVision/Functional.cs` converts the returned tensor to the wrong dtype. 
Working pytorch code:
```python
import torch
import torchvision.transforms.functional as F
img1 = torch.randn((1,32,32)).to(torch.uint8)
img2 = F.adjust_contrast(img1, 2)
assert(img1.dtype == img2.dtype)
```
Non working torchsharp code:
```c#
using TorchSharp;
using F = TorchSharp.torchvision.transforms.functional;
var img1 = torch.randn(1,32,32).to(ScalarType.Byte);
var img2 = F.adjust_contrast(img1, 2);
Debug.Assert(img1.dtype == img2.dtype);
```
```
Process terminated. Assertion failed.
at TorchSharpExample.Program.Main(String[] args)
```
The original torchsharp code was introduced in this commit https://github.com/pytorch/vision/commit/e79caddf7490a1cb7f460fe353880fb8b54505a8#diff-49 …

Fix the datatype of the returned tensor in Blend function

---

azure-pipelines.yml
build/ci/job-template.yml

Since Ubuntu CI always fails, script is used UseDotNet@2, there should be no need to use apt install dotnet.🤔

Remove apt install dotnet

---

src/TorchVision/Utils.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestTorchVisionUtils.cs

I find the make_grid/save_image functions in torchvision.utils a quick and easy way to save an image batch to png/jpg...etc.
The code might need some additional TorchSharp specific changes.

Port torchvision.utils.make_grid and torchvision.utils.save_image from pytorch.

---

src/Native/LibTorchSharp/THSJIT.cpp
src/Native/LibTorchSharp/THSLoss.cpp
src/Native/LibTorchSharp/THSModule.cpp
src/Native/LibTorchSharp/THSNN.cpp
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/Utils.cpp
src/Native/LibTorchSharp/Utils.h

While NULL is defined as 0 which is a valid default value for the float, the default value should be 0.0f
This fixes the compiler warning:
```
TorchSharp/src/Native/LibTorchSharp/THSTensor.cpp(389,5): error G13A67890: converting to non-pointer type ‘float’ from NULL [-Werror=conversion-null] [TorchSharp/src/Native/build.proj]
389 |     CATCH_RETURN(float, NULL, (float)(tensor->data_ptr<c10::Half>())[i]);
|     ^~~~~~~~~~~~
```

Fix semantic error in THSTensor.cpp

---

RELEASENOTES.md
build/BranchInfo.props
src/Examples/Examples.csproj
src/TorchSharp/TorchSharp.csproj
src/TorchVision/TorchVision.csproj
test/TorchSharpTest/TestJIT.cs

SkiaSharp was affected by the WEBP vulnerability, which was addressed in v2.88.6

Update to SkiaSharp 2.88.6

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/NN/Module.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/TestLoadSave.cs

Added a bug fix where when you load in a model in non-strict mode, if it skips a parameter load it still reads it in so that the BinaryReader can seek forwards to the next tensor. 
NOTE: I also modified the behavior so that if you specify a parameter in the "skip" list, then it no longer requires the dimensions to match. 
I haven't updated the release notes either, what version should I list this bugfix under? 
Also, as part of this feature I wrote a unit test which covers the unit test from the previous PR, so I removed the old one.

BugFix: When loading non-strict, make sure to read in the tensor bytes

---

RELEASENOTES.md
src/TorchSharp/Tensor/TensorExtensionMethods.cs

Following the other PR, I wrote an extension method which returns the size of a ScalarType using a big switch. 
Niklas - you initially wrote to write it in ScalarExtensionMethods, but I saw that there were other extension methods written for ScalarType in TensorExtensionMethods, so I thought it more appropriate to be there. If you think otherwise, let me know and I'll move it back to ScalarExtensionMethods.

Added extension method ScalarType.ElementSize()

---

src/TorchSharp/Optimizers/NAdam.cs
test/TorchSharpTest/TestTraining.cs

Following the issue [here](https://github.com/dotnet/TorchSharp/issues/1154), the mu_product is now initialized to 1.

Updated mu_product initialization

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/NN/Module.cs
src/TorchSharp/Tensor/Tensor.cs

Added to_type alias for converting types to `short`, `half`, `bfloat16`, `cfloat`, `cdouble`.

Added to type alias for short, half, bfloat16, cfloat, cdouble

---

RELEASENOTES.md
build/BranchInfo.props
src/Native/LibTorchSharp/THSAutograd.cpp
src/Native/LibTorchSharp/THSAutograd.h
src/TorchSharp/Autograd.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSAutograd.cs
src/TorchSharp/Tensor/torch.LocallyDisablingGradientComputation.cs
test/TorchSharpTest/TestTorchSharp.cs

Added support for torch.inference_mode() context manager, for faster evaluation.
In which should file should I add a unit test?
Also, does it make sense for a unit test where I enabled inference_mode, and then call torch.is_inference_mode_enabled() to confirm?

Added inference mode context manager

---

src/TorchSharp/NN/Normalization/LayerNorm.cs

This is essentially to allow the bias parameter, which setting to false allows computing layernorms without a bias.

Implement LayerNorm module in terms of functional.layer_norm.

---

RELEASENOTES.md
src/Python/exportsd.py
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/Optimizer.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs

While adding the functionality for saving the optimizer state_dict in the pytorch format, I encountered an issue that I couldn't resolve externally. 
When looking at an optimizer state_dict in Python, they have an index mapping between the parameter_group and the state group. 
E.g., see here a sample state_dict of an Adam optimizer:
```json
{
"state": {
0: {
"step": tensor(1.),
"exp_avg": tensor(...),
"exp_avg_seq": tensor(...)
},
1: {
"step": tensor(1.),
"exp_avg": tensor(...),
"exp_avg_seq": tensor(...)
},
},
"param_groups": [
{
"lr": 0.001,
"betas": [
0.8,
0.9
],
"eps": 1e-08,
"weight_decay": 0,
"amsgrad": false,
"maximize": false,
"foreach": null,
"capturable": false,
"differentiable": false,
"fused": null,
"params": [
0,
1
]
}
]
}
```
For TorchSharp, there is no need for the params, …

Added state index ref to optimizer state dict

---

RELEASENOTES.md
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/Optimizer.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Fixes: https://github.com/dotnet/TorchSharp/issues/1172

Fix optimizer load state dict copy tensor by reference

---

RELEASENOTES.md
src/TorchSharp/NN/Module.cs
src/TorchSharp/NN/ParameterDict.cs
src/TorchSharp/NN/ParameterList.cs
src/TorchSharp/Tensor/TensorExtensionMethods.cs
test/TorchSharpTest/NN.cs

Fixes https://github.com/dotnet/TorchSharp/issues/1148 and https://github.com/dotnet/TorchSharp/issues/1179.
I went on a whim and attempted to make a style change on the _toEpilog method. If you see a fatal error or prefer to leave it as it used to be - no problem, I'll revert that change.
Main changes:
1] Merged the three _toEpilog methods into one method.
2] Instead of re-iterating the fields every time and reassigning the parameters, I build a dictionary of the fields and as we go through the registered parameters we check if they have a field, and if so - assign it. Saves us from duplicating the code which handles the moving of the parameters.
3] When moving Parameters, we do it in a "torch.no_grad()" scope to avoid having autograd track the movement and so that the resulting tensor …

Fixed `Module.to()` bugs with `ParameterList` and `ParameterDict`, and with autograd tracking movements between CPU & GPU

---

RELEASENOTES.md
src/TorchSharp/NN/Module.cs
test/TorchSharpTest/NN.cs

Validate the target data type when converting a Module using `to()`

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSJIT.cpp
src/Native/LibTorchSharp/THSJIT.h
src/TorchSharp/JIT/ScriptModule.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSJIT.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Following the discussion on https://github.com/dotnet/TorchSharp/discussions/1126.

Added set_attribute + added script module to to include attributes

---

RELEASENOTES.md
src/Native/LibTorchSharp/THSModule.cpp
src/Native/LibTorchSharp/THSNN.h
src/Native/LibTorchSharp/THSTensor.cpp
src/Native/LibTorchSharp/THSTensor.h
src/TorchSharp/NN/Module.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSNN.cs
src/TorchSharp/PInvoke/LibTorchSharp.THSTensor.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

Fixing https://github.com/dotnet/TorchSharp/issues/1191
Modified to behave like PyTorch / LibTorch, see here: https://github.com/pytorch/pytorch/blob/main/torch/csrc/api/src/nn/module.cpp#L253 and https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L836
Important to note: This introduces a breaking change, as calling zero_grad() by default now converts gradients to null. 
This is probably a good breaking change, because up until now it wasn't consistent and modules that were managed by LibTorch (like Linear) had their gradients set to null whereas the modules managed by TorchSharp had their gradients set to zero.

Fixed gradients moving and zeroing

---

src/TorchSharp/DisposeScope.cs
src/TorchSharp/NN/Module.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestDisposeScopes.cs

Following the previous PR (a few weeks ago), we talked about the option for attaching a tensor to a different dispose scope, in addition to moving to the outer and detaching completely.

Adding an option to attach a tensor to a different dispose scope

---

src/TorchSharp/Device.cs
src/TorchSharp/Tensor/Factories/Tensor.Factories.cs
test/TorchSharpTest/TestTorchTensor.cs

Fixes https://github.com/dotnet/TorchSharp/issues/1198.
I tested it out locally - I added the DLL and the libtorch-cuda package, and it worked. I then tried it with the libtorch-cpu package and I confirmed that it didn't crash. 
I was going to add a test for it - but in our CUDA tests we always check that cuda is available, and then that defeats the purpose since checking if it is available initializes it. 
Do you have any suggestions?

Added to always initialize CUDA 

---

RELEASENOTES.md
build/BranchInfo.props
src/TorchSharp/Functional.cs
test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj
test/TorchSharpTest/TestJacobian.cs

Initial implementation of the jacobian method, based on https://pytorch.org/docs/stable/_modules/torch/autograd/functional.html#jacobian .
Resolves #1149.
Omits several options from the PyTorch implementation, such as `create_graph`, `strict`, `vectorize` and `strategy`.
It behaves as if `create_graph=False`, `strict=False`, `vectorize=False` and `strategy="reverse-mode"`.
I added an example of usage in the documentation of the method itself.
@NiklasGustafsson

Implementation of jacobian method, based on PyTorch implementation

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

When playing with the schedulers, I noticed that they didn't match the results coming from PyTorch, so I updated the behavior. 
Justifications:
- Fixing the parentheses in the LinearLR `get_lr` function: https://github.com/pytorch/pytorch/blob/HEAD/torch/optim/lr_scheduler.py#L590-L591
- Removing the loop which sets the InitialLearningRate in the `LRScheduler` constructor: In the PyTorch code [here](https://github.com/pytorch/pytorch/blob/HEAD/torch/optim/lr_scheduler.py#L45-L46) they don't force-set the initial_lr, but rather set it if it wasn't there yet. In TorchSharp the initial_lr value is always set, and therefore that loop shouldn't be called. With one scheduler it isn't an issue, but with multiple you have the issue that each scheduler re-sets the initial_lr, and then sets the …

Added a fix for LinearLR scheduler, and updated behavior of all schedulers to match PyTorch

---

RELEASENOTES.md
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

I encountered a bug with Module.load(), when I gave it a deflate stream. Turns out that when you call `stream.Read(buffer, start, length)` there is no guarantee that it will read length even if there are more bytes in the stream. 
I had assumed that if there were bytes to read, then it would always read to the maximum. Turns out that `DeflateStream` it will sometimes return after having read a partial length, because of some internal logic. So even though I requested the next 1024 bytes, it can return 788 bytes and then in the next request return 1024 again.

Fixed issue with Module.load() with deflate stream

---

RELEASENOTES.md
src/TorchSharp/NN/Pooling/AvgPool1D.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs

The modification of the AvgPool1D stride parameter defaulting to kernelSize is as per the documentation here:
https://github.com/pytorch/pytorch/blob/main/torch/nn/functional.py#L354-L355
And the implementation of the module here:
https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/pooling.py#L549-L550
On the way, I also fixed the 0D tensor string printing. 
Fixes: https://github.com/dotnet/TorchSharp/issues/1249 and https://github.com/dotnet/TorchSharp/issues/1250.
@NiklasGustafsson  Question: The PyTorch parameter is named `kernel_size` whereas in TorchSharp it's written as `kernelSize`. Is it worth at this point to change the naming to match PyTorch?

Fixing 1249 and 1250 (avg pool1d + 0D string conversion)

---

RELEASENOTES.md
src/TorchSharp/Torch.cs

There was an ordering error between segments of the static class initializer for the partial class 'torch' that impacted the loading of

Address issue with ordering of initializations in the torch cctor.

---

RELEASENOTES.md
src/TorchSharp/Torch.cs
test/TorchSharpTest/TestTorchSharp.cs

Hello! I've tried to add two methods `fuse_conv_bn_weights` and `fuse_linear_bn_weights` in `torch.nn.utils`. 
Since it's my first pull request that modifies the code, could someone please give me some advice? In fact I'm not sure about the following things:
- Am I required to add a high coverage unit test? Meanwhile, where could I put some tests?
- I've found some similar methods like `clip_grad_value_` does not have a related unit test, and `parameters_to_vector`'s tests are placed in `TestTorchSharp` and named `UtilsPtoV`, so I'm a bit confused with that.
- (Actually I haven't check whether the two methods could work correctly, although I believe they do, since what I have done is just translating the python codes into csharp.)
- Should I always dispose all the temporary tensors, or …

'fuse_conv_bn_weights' and 'fuse_linear_bn_weights' in 'torch.nn.utils'

---

RELEASENOTES.md
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/Tensor/torch.Tensors.cs
test/TorchSharpTest/TestTorchSharp.cs

fixes #1279 
1. add support for `Float16` and `BFloat16`
2. correct the result (`eps` should not be equal to c# `Epsilon`, and meanwhile `tiny` is not `eps`.)
3. add more fields in `FInfo`
4. `torch.set_default_dtype` will no longer accept non-floating types
Note: `Categorical.entropy`, `_CorrCholesky.check`, `Distribution.ClampProbs`, `FisherSnedecor.rsample`, `Gamma.rsample`, `Geometric.rsample`, `distributions.Gumbel`, `Laplace.rsample`, `SigmoidTransform._call` and `SigmoidTransform._inverse` are influenced. **I'm not sure whether they could work correctly now.**

correct torch.finfo

---

src/Python/exportsd.py

An error occurred when trying to save the downloaded pretained model:
```python
states = weight.get_state_dict()
exportsd.save_state_dict(states, file)
```
(where `weight` is something like `torchvision.models.AlexNet_Weights.IMAGENET1K_V1`)
([full codes here](https://huggingface.co/spaces/yueyinqiu/vision-TorchSharp-generator/tree/main))

in exportsd.py, call detach() before numpy()

---

RELEASENOTES.md
src/TorchSharp/Tensor/Factories/Tensor.Factories.cs

`torch.normal` is returning a non-leaf tensor (and also no names).

leaf normal

---

RELEASENOTES.md
src/Examples/AdversarialExampleGeneration.cs
src/FSharp.Examples/AdversarialExampleGeneration.fs
src/TorchSharp/NN/Module.cs
src/TorchSharp/Optimizers/ASGD.cs
src/TorchSharp/Optimizers/Adadelta.cs
src/TorchSharp/Optimizers/Adagrad.cs
src/TorchSharp/Optimizers/Adam.cs
src/TorchSharp/Optimizers/AdamW.cs
src/TorchSharp/Optimizers/Adamax.cs
src/TorchSharp/Optimizers/NAdam.cs
src/TorchSharp/Optimizers/Optimizer.cs
src/TorchSharp/Optimizers/RAdam.cs
src/TorchSharp/Optimizers/RMSprop.cs
src/TorchSharp/Optimizers/Rprop.cs
src/TorchSharp/Optimizers/SGD.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/NN.cs
test/TorchSharpTest/TestAutogradFunction.cs
test/TorchSharpTest/TestNNUtils.cs
test/TorchSharpTest/TestTorchTensor.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

property grad

---

src/TorchSharp/Torch.cs

Improves debugging of native library loading exceptions by printing any unhandled exceptions to the trace log.
Fixes #1310

Append unhandled exception message to trace

---

RELEASENOTES.md
src/TorchSharp/DataLoader.cs

fixes #1314 
I have also found that our data loader is not same as the current PyTorch one.
But currently I'm busy with my stuffs. @NiklasGustafsson If you are going to publish a new release and think this pr it's ok, then maybe merge this to fix that problem, otherwise maybe waiting for more commits later. (I won't touch this at least in a week.)

exposes the field in DataLoader

---

src/TorchSharp/NN/Module.cs
src/TorchSharp/Utils/TensorAccessor.cs
test/TorchSharpTest/NN.cs

Add CopyTo/From overloads to TensorAccessor for Span<T>.

Module hooks don't depend on the forward() signature.

---

azure-pipelines.yml
pkg/pack.proj

The pack.proj used here was Restoring and Packing in the same MSBuild evaluation, causing it to not get any of the nuget generated props or targets.
Fix by making these separate and calling as a separate evaluation.
That requires configuration to be specified since intermediate directory includes configuration (erroneously).
This should fix the official build.  It may not fix the sln pack scenario, since I think that still will not restore in a separate evaluation.  A better fix would be to include all projects in the SLN - but I'm focused on the minimal fix ATM.

Restore before packing

---

pkg/Directory.Build.targets

This is needed for APICompat which loads references when comparing assemblies.  It get's those references from the project's resolved references (packages / projects) and the nupkgproj's were returning a bogus path.  This target makes them return a path from the prep folder where they grab their content -- if it exists.

Make GetTargetPath return valid path for nupkgprojs

---

Directory.Build.props
pkg/Directory.Build.targets

These don't contain managed surface area so running APICompat doesn't provide much value.  Disable it to reduce the time spent and eliminate the need to record and restore previous versions of libtorch.

Disable package validation for libtorch packages

---

RELEASENOTES.md
src/TorchSharp/ConcatDataset.cs
src/TorchSharp/DataLoader.cs
src/TorchSharp/Dataset.cs
src/TorchSharp/Utils/TensorDataset.cs
test/TorchSharpTest/TestDataLoader.cs

https://github.com/dotnet/TorchSharp/discussions/1348#discussioncomment-10035168
- add `torch.utils.data.ConcatDataset`
- The parameter of `DataLoader`s has been relaxed to `IDataset<out T>` (a new covariant interface), thus accepting the concated dataset
- now `Dataset<T>` implements `IDataset<T>`
- `Dataset` implements both `IDataset<Dictionary<string, Tensor>>` and `IDataset<IReadOnlyDictionary<string, Tensor>>`
- `IterableDataset` implements `IDataset<IList<string, Tensor>>` and `IDataset<IEnumerable<string, Tensor>>`
- parameter of collate functions has been relaxed to `IReadOnlyList`

concat dataset

---

RELEASENOTES.md
src/TorchSharp/LinearAlgebra.cs
test/TorchSharpTest/LinearAlgebra.cs

The docs of this method specify:
```
<param name="ord">Order of norm. Default: 2</param>
```
Said default was however not actually implemented

`torch.linalg.vector_norm` : Set `ord` default as specified in docs

---

RELEASENOTES.md
src/TorchSharp/Tensor/Tensor.cs

Fixes #692 
TLDR: `Tensor.backward` has a different parameter order compared to PyTorch and also swaps `retain_graph` and `create_graph` in its internal function call.
See https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html for backward's function signature:
`Tensor.backward(gradient=None, retain_graph=None, create_graph=False, inputs=None)`
The current TorchSharp version's function signature is:
`Tensor.backward(grad_tensors=null, create_graph=false, retain_graph=false, inputs=null)`
Note the difference between the ordering of `retain_graph` and `create_graph`. `Tensor.backward` is just a wrapper to `torch.autograd.backward` which has a function signature of:
`autograd.backward(tensors, grad_tensors=null, retain_graph=null, create_graph=false, inputs=null)`
This means …

Fixing Tensor.backward's function signature

---

RELEASENOTES.md
src/TorchSharp/DisposeScope.cs
src/TorchSharp/ThreadDisposeScopeStatistics.cs
test/TorchSharpTest/TestDisposeScopesPackedSequence.cs
test/TorchSharpTest/TestDisposeScopesStatisticsBase.cs
test/TorchSharpTest/TestDisposeScopesStatisticsPackedSequence.cs
test/TorchSharpTest/TestDisposeScopesStatisticsPackedSequenceUnscoped.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensor.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensorUnscoped.cs

Added test to verify that attaching an unscoped Tensor or PackedSequence no longer decrements DetachedFromScopeCount, making it possibly become negative. Note also removed the scope counting tests from TestDisposeScopesPackedSequence, which now only tests disposal behavior. Metrics are now all tested in a dedicated set of test fixtures.
Added additional tests to document behavior and improve test coverage for both Tensor and PackedSequence objects, in scenarios for both scoped and unscoped instances of these objects (total of 4 new fixtures). This should help future changes as one can see what the system does to count the statistics.
Tests reflect the expected behavior based on the doc comments for ThreadDisposeScopeStatistics. Note that the ThreadTotalLiveCount property is still …

Resolves #1387 and backfill tests for ThreadDisposeScopeStatistics

---

RELEASENOTES.md
docfx/articles/memory leak troubleshooting.md
docfx/articles/memory.md
src/TorchSharp/DisposeScope.cs
src/TorchSharp/DisposeScopeManager.cs
src/TorchSharp/NN/Utils/PackedSequence.cs
src/TorchSharp/Tensor/Tensor.cs
src/TorchSharp/ThreadDisposeScopeStatistics.cs
test/TorchSharpTest/TestDisposeScopes.cs
test/TorchSharpTest/TestDisposeScopesStatisticsBase.cs
test/TorchSharpTest/TestDisposeScopesStatisticsPackedSequence.cs
test/TorchSharpTest/TestDisposeScopesStatisticsPackedSequenceUnscoped.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensor.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensorUnscoped.cs
test/TorchSharpTest/TestDisposeScopesStatisticsToString.cs
test/TorchSharpTest/TestTraining.cs

Improve visibility of disposables (Tensor and PackedSequence) to make memory leaks easier to troubleshoot. No breaking interface changes. This resolves #1390.
This PR is what I'd actually like to see for object lifetime statitics. It gives complete statistics for object creation and disposables whether in a DisposeScope or not, and accurate Attach/Detach counts. Lastly the ThreadTotalLiveCount is no longer estimated, it is exact. Also added documentation on how to use the statistics for troubleshooting memory leaks.
New Documentation:
memory leak troubleshooting.md - provides practical guidance on how to use the changes of this PR for useful troubleshooting of memory issues.memory.md was also updated to link to this document.
New Interface Members
* DisposedOutsideScopeCount - # of …

Better metrics

---

RELEASENOTES.md
src/TorchSharp/Tensor/Factories/tensor_Complex.cs
src/TorchSharp/Tensor/Factories/tensor_double.cs
src/TorchSharp/Tensor/Factories/tensor_float.cs
src/TorchSharp/Tensor/Factories/tensor_long.cs
src/TorchSharp/Tensor/Tensor.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensor.cs
test/TorchSharpTest/TestDisposeScopesStatisticsTensorUnscoped.cs
test/TorchSharpTest/TestTorchTensor.cs

This resolved the orphan tensor issue. 
Please note for tensor creation, I removed branches that were checking if device was supplied - this branch would always take precedence over the else branch that was checking dtype, because of the `InitializeDevice` call at the beginning. Not sure why that branch was there, since the tensor is being created on the correct device initially.
Since there was much duplication related to managing disposing the initial tensor when a dtype conversion was necessary, I've created new internal factory method `Tensor.InstantiateTensorWithLeakSafeTypeChange` to manage this. I can't say I love the name, but it's accurate, suggestions welcome. Also if there is a better place to put that method am happy to move it.
In the case of complex numbers, there were …

Fix memory leaks in .ToTensor,  resolves #1392

---

test/TorchSharpTest.WithCudaBinaries/TorchSharpTest.WithCudaBinaries.csproj

Fixed, thanks @NiklasGustafsson I'll remember this in the future. I assume no need to update release notes on this one.

Add new test fixtures to CudaBinaries project resolves #1394

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs

`torch.optim.lr_scheduler.LinearLR` `end_factor` default was `5`, but should be `1.0`.
Most probably, it would be a typo influenced from `total_iters` default (`5`).
See also https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.LinearLR.html

Fix LinearLR end_factor default.

---

RELEASENOTES.md
src/TorchSharp/Optimizers/LRScheduler.cs
test/TorchSharpTest/TestTorchTensorBugs.cs
test/TorchSharpTest/TestTraining.cs

`torch.optim.lr_scheduler.PolynomialLR` `power` was typed `int`, but should be `double`.
Non-integer `power` is widely used for common training recipe.
E.g. `torchvision`'s pre-trained semantic segmentation models uses `PolynomialLR` as main LR scheduler with `power = 0.9`; https://github.com/pytorch/vision/blob/main/references/segmentation/train.py#L201
See also https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.PolynomialLR.html

Fix PolynomialLR power type.
